name: ypp
channels:
    - conda-forge
dependencies:        
    - sympy
    - pandas
    - graphviz 
    - scikit-learn
    - ipywidgets
    - ipywebrtc
    - matplotlib
    - pip:
        - -rrequirements.txt
